# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Global configuration
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Web Server - Ubuntu 22.04
  config.vm.define "web-server" do |web|
    web.vm.box = "ubuntu/jammy64"
    web.vm.hostname = "web-server"
    
    # Network configuration
    web.vm.network "public_network"
    web.vm.network "private_network", ip: "192.168.56.10"
    
    # Synced folder for website
    web.vm.synced_folder "./website/", "/var/www/html/", 
      owner: "www-data", group: "www-data"
    
    # VM configuration
    web.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-web-server"
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    # Provisioning
    web.vm.provision "shell", path: "scripts/provision-web-ubuntu.sh"
  end

  # Database Server - CentOS 9
  config.vm.define "db-server" do |db|
    db.vm.box = "generic/centos9s"
    db.vm.hostname = "db-server"
    
    # Network configuration
    db.vm.network "private_network", ip: "192.168.56.20"
    db.vm.network "forwarded_port", guest: 3306, host: 3307

    # Synced folder for database scripts
    db.vm.synced_folder "./database/", "/vagrant/database/", type: "rsync"
    
    # VM configuration
    db.vm.provider "virtualbox" do |vb|
      vb.name = "centos-db-server"
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    # Provisioning
    db.vm.provision "shell", path: "scripts/provision-db-centos.sh"
  end

end